APP_NAME='zenspace_iot_gateway'
#ZEN_URL='https://zensapce-staging.herokuapp.com/api/iot/reservation/retrieve/'
#ZEN_STATE_URL='https://zensapce-staging.herokuapp.com/api/iot/pod/save-state/'
ZEN_URL='https://zenspace-production.herokuapp.com/api/iot/reservation/retrieve/'
ZEN_STATE_URL='https://zenspace-production.herokuapp.com/api/iot/pod/save-state/'
